Serviceのテスト
aya030/ItemCRUD pull request #4
Opened 2022-06-09 04:50 UTC by aya030

サービスクラスのJUnitテストを行いました

2022-06-09 13:00 UTC, yoshi-koyama commented on build.gradle
> +    testImplementation 'org.mockito:mockito-junit-jupiter:3.6.0'
spring boot starter testに入っているはず。
https://spring.pleiades.io/spring-boot/docs/2.0.2.RELEASE/reference/html/boot-features-testing.html#boot-features-test-scope-dependencies

消してみて動かしてみてください。

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/controller/ItemControllerTest.java
> +public class ItemControllerTest {
これは何でしょうか？
消し忘れ？

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +@Import(Item.class)
これ必要でしょうか？

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	@DisplayName("検索idに1を渡すとid=１に基づいたデータと一致する")
![badge](https://img.shields.io/badge/review-imo-orange.svg)
メソッド名を日本語にしてもいいと思います。

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/resources/test.properties
> +spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
Serviceの単体テストならこのあたり必要ないはず。

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +@SpringBootTest(classes = ItemService.class)
Serviceの単体テストであればSpringBootTestは使わないようにしたいです。
※SpringBootTestはBeanの起動が必要なため

それを意図してclassesで絞ってくれているのかな？

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		item.setId(1);
前処理ではデータベースなどのデータ準備をしましょう。
Itemのインスタンス生成は各テストメソッドで行えばいいです。
またsetterでなくconstructorによってインスタンス生成しましょう。

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	@DisplayName("検索idにNULLを渡してもNullPointerExceptionにならない")
このテストケースについて質問です！ 🚀 
- idにnullではなく1をわたしていますが意図はありますか？（ただの間違い？）
- idにnullが渡される場合の返り値の期待値は空のOptionalではないでしょうか？
  - そもそもnullが渡されない想定ならテストも不要かも（考え方次第）

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	@DisplayName("insertOne()を呼び出したら1回実行される")
![badge](https://img.shields.io/badge/review-imo-orange.svg)
```suggestion
	@DisplayName("登録処理を呼び出したときにmapperの登録処理が1回のみ実行され正常に処理が完了すること")
```

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).insertOne(item2);
この検証不要ですかね？

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	@DisplayName("updateOne()を呼び出したら1回実行される")
何が１回実行されるのかを書きたいですね

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		assertEquals(expected,itemService.initRadioCategory());
```suggestion
		assertEquals(expected, itemService.initRadioCategory());
```

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/resources/data.sql
> +INSERT INTO itemtable (name, price, category, num)
これもServiceのテストでは不要ですね。

2022-06-09 13:00 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		item.setId(1);
少し話がそれますが、テストにおいては過度に共通化はしないことが推奨されています。
Googleのテストブログです↓
https://testing.googleblog.com/2019/12/testing-on-toilet-tests-too-dry-make.html

理由としてはテストコードに対するテストは存在しないため共通化を避けて１つ１つのケースがより説明的であるほうが読みやすいからと考えます。
Given-When-ThenやArrange-Act-Assertといった言葉があります。
たとえば、
```markdown
Given: 存在するidで
When: 検索すると
Then: Itemが1件返されること
```
のようなケースを想定したときにテストコード内に上記と同じ流れで記述するのがベターです。

こちら、必ず従わないといけないというわけではないですが、覚えておいてもらえると嬉しいです。

2022-06-11 02:30 UTC, aya030 commented on build.gradle
> +    testImplementation 'org.mockito:mockito-junit-jupiter:3.6.0'
消しても動きました

2022-06-11 02:30 UTC, aya030 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +@Import(Item.class)
先にコントローラーのテストから始めようと思い作りましたが、サービスを先に書いたので残ったままでした。

2022-06-11 02:44 UTC, aya030 commented
サービスクラスのテストの修正を行いました。
①アノテーションの削除　
[37798d4](https://github.com/aya030/ItemCRUD/pull/4/commits/37798d4ecdc4f875f3b86aede31aad3242acbe5f)
※SpringBootTestアノテーションがないとテストが動きませんでした。。
②不要なテストの削除　
[9d5a3b7](https://github.com/aya030/ItemCRUD/pull/4/commits/9d5a3b732c8c4cd9a4d97ae31c84eda594270357)
③テスト名の修正、メソッド名を日本語、DisplayNameの削除　
[4ebf95c](https://github.com/aya030/ItemCRUD/pull/4/commits/4ebf95c225015fe26c93d15a0032f769f7d14e15)

2022-06-11 03:30 UTC, yoshi-koyama commented on src/main/java/com/example/demo/controller/ItemController.java
> +//@RequestMapping("/items")
これどういう意図でコメントアウトしていますか？

2022-06-11 03:30 UTC, yoshi-koyama commented on src/test/java/com/example/demo/controller/ItemControllerTest.java
> +//@Configuration
このあたりもいらないなら消したいところ。

2022-06-11 03:30 UTC, yoshi-koyama commented on src/test/java/com/example/demo/controller/ItemControllerTest.java
> +	private MockMvc mockMvc;
ServiceとControllerのテストはPR分けても良かったかも。
話があちこちに言ってしまうのでますはServiceの単体テストを完成させることを優先したほうがPRが早めにマージできますね。

2022-06-11 09:05 UTC, YudaiNoda3576 requested changes
色々とコメントしていますが、ちゃんと書けてると思います！
テストの考え方みたいなものがピンと来てないだけだと思うので、少しずつ修正して行きましょう！:smile:

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	public void 検索idに1を渡すとidが１に紐づいたデータと一致する() {
テストケースがちょっと分かりづらいように感じます！
`該当するIDのItemが一件取得されること`
くらいでも良いのかなと！

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		int id = 1;
このテストケースであればmid = nullが正しいかと！

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	public void idが2の更新処理を呼び出したときにmapperの更新処理が1回のみ実行され正常に処理が完了すること() {
`該当のIDのデータが正常に更新されること`
くらいで良いかと！

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).updateOne(2, "マーガレットピアス", 2400, "ピアス", 3);
verifyメソッドはモックのメソッドが何回呼ばれているかを検証するメソッドになるため、
今回は、ちゃんとデータが更新されているか？を検証する必要があります！

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	public void idが1の削除処理を呼び出したら削除処理が1回のみ実行され正常に処理が完了すること() {
`該当のIDのデータが一件削除されること`
くらいで良いかと！

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).insertOne(item);
データが新規登録されているか？を検証する必要がありますね！

2022-06-11 09:05 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).deleteOne(1);
データが削除されているか？を検証する必要があります！
例えばデータの件数が１件から０件になるみたいなイメージです！

2022-06-13 01:09 UTC, aya030 commented
テスト内容を一部変更しました。

該当するIDのItemが一件取得されること()
[60ff69e](https://github.com/aya030/ItemCRUD/pull/4/commits/60ff69e89507f10c9934fac0f9172da48d0535f9)

検索idにNULLを渡してもNullPointerExceptionにならない()
[0bc669e](https://github.com/aya030/ItemCRUD/pull/4/commits/0bc669e1e622967414e574d586c2062031a7dc87)

データをリスト表示するとデータ数が一致する()
[6b5e8f0](https://github.com/aya030/ItemCRUD/pull/4/commits/6b5e8f07489454c20ac6f20a27f050c36c3cdd48)

データが新規登録されること()
[cff7685](https://github.com/aya030/ItemCRUD/pull/4/commits/cff76850303e0f51a648b891c0bd6c513c921068)

該当のIDのデータが正常に更新されること()
[c53a67d](https://github.com/aya030/ItemCRUD/pull/4/commits/c53a67d9432a783930f5d64a26725778eeab12f7)

2022-06-13 11:39 UTC, yoshi-koyama commented on build.gradle
> +    testImplementation 'org.mockito:mockito-junit-jupiter:3.6.0'
消して動いたのであれば消しちゃいましょう！

2022-06-13 11:39 UTC, yoshi-koyama commented on src/test/java/com/example/demo/controller/ItemControllerTest.java
> +public class ItemControllerTest {
PRわけるということで合意

2022-06-13 11:44 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).deleteOne(1);
@aya030  cc: @YudaiNoda3576 
こちらServiceの単体テストでMapperはMockかするので件数が変わることの確認はできないですね。
↑という前提がゆーだいさんに伝わっていないかもしれませんので説明いただくのがいいかと思います！

ゆーだいさんのおっしゃる検証はMapperの単体テストでやりましょう。

2022-06-13 14:48 UTC, aya030 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).deleteOne(1);
@yoshi-koyama 
@YudaiNoda3576 
DBには接続しておらず、「MapperをMock化してデータがあるように見せているだけ」なので、deleteOneをしようとしてもデータが消えることはない。
という感じでしょうか。

2022-06-13 19:42 UTC, YudaiNoda3576 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		verify(itemMapper, times(1)).deleteOne(1);
@aya030 @yoshi-koyama 
あ、すみません！
完全に勘違いしてました😓
かえって混乱させてしまい大変失礼しました🙇‍♂️

小山さんフォロー頂きありがとうございます🙏

2022-06-14 02:05 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	Item item = new Item();
Itemの初期化は各テストケースで実施しましょう。

2022-06-14 02:05 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	ItemService itemService = new ItemService(itemMapper);
↓で動きませんか？
```suggestion
	ItemService itemService
```

2022-06-14 02:05 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	public void 検索idにNULLを渡してもNullPointerExceptionにならない() {
int型はプリミティブ型なのでnullになることはありえませんのでこのケースいらないと思います。

2022-06-14 02:05 UTC, yoshi-koyama commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		assertThat(itemMapper.findAll()).hasSize(2);
こちら、わたしが試しにassertJを使ってみてといった箇所ですが、同じ検証が2つあるのでどちらかにしましょう。
試しにassertJを使っているコードを残しておきたいということならばコメントを残しましょう。

2022-06-14 10:26 UTC, aya030 commented
行なったこと
Itemの初期化を各テストケースに記述
[6578d21](https://github.com/aya030/ItemCRUD/pull/4/commits/6578d21bf597d496f4dee612c8e9c422c561eaad)

ItemService itemService;変数の指定のみに変更
[2454dfb](https://github.com/aya030/ItemCRUD/pull/4/commits/2454dfb6d32ab4c351e0a71e57aa2a9cffe82524)

Nullになることはないので、
検索idにNULLを渡してもNullPointerExceptionにならない()テストを削除
[aed098f](https://github.com/aya030/ItemCRUD/pull/4/commits/aed098f348fa095ff094cbf6ec623ea217437cb3)

assertJを使ったテストをコメント化
[bf4aee3](https://github.com/aya030/ItemCRUD/pull/4/commits/bf4aee3f66de5ca4d8f8ce6cc7188312053c7e51)

該当のIDのデータが一件削除されること()のテストケースをdeleteOneが1回実行されているかに変更
[6dcd4a4](https://github.com/aya030/ItemCRUD/pull/4/commits/6dcd4a4b3196f18bbdf5bdf72f6db6c318c745c4)

2022-06-14 12:00 UTC, aya030 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	Item item = new Item();
Itemの初期化を各テストケースに記述
[6578d21](https://github.com/aya030/ItemCRUD/pull/4/commits/6578d21bf597d496f4dee612c8e9c422c561eaad)

2022-06-14 12:00 UTC, aya030 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	ItemService itemService = new ItemService(itemMapper);
消しても動きました！
ItemService itemService;変数の指定のみに変更
[2454dfb](https://github.com/aya030/ItemCRUD/pull/4/commits/2454dfb6d32ab4c351e0a71e57aa2a9cffe82524)

2022-06-14 12:01 UTC, aya030 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +	public void 検索idにNULLを渡してもNullPointerExceptionにならない() {
検索idにNULLを渡してもNullPointerExceptionにならない()テストを削除しました。
[aed098f](https://github.com/aya030/ItemCRUD/pull/4/commits/aed098f348fa095ff094cbf6ec623ea217437cb3)

2022-06-14 12:01 UTC, aya030 commented on src/test/java/com/example/demo/service/ItemServiceTest.java
> +		assertThat(itemMapper.findAll()).hasSize(2);
assertJを使ったテストの方をコメント化
[bf4aee3](https://github.com/aya030/ItemCRUD/pull/4/commits/bf4aee3f66de5ca4d8f8ce6cc7188312053c7e51)

2022-06-14 12:53 UTC, merged